### PR TITLE
feat: rely on ARC_ENV instead of NODE_ENV

### PR DESCRIPTION
**Pull request by salper**
### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `main`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [x] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [x] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [x] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by salper** [comment]
My take on this: relying on `NODE_ENV` is error prone as it can take any value depending on the local implementation (value clash or mismatch). Looking at arc behaviour, it seems that `ARC_ENV` is always set by the CLI or during deployment on AWS, and considering that it's an internal variable, it's legit to control its values and to rely on it for the internal behaviour of the library. In a larger manner, I personally think that all the `arc` code should rely on `ARC_ENV` instead of `NODE_ENV`. Let me know what you think of it.

**Comment by ryanblock** [comment]
This is absolutely the correct approach and is coming in [Architect 10](https://github.com/architect/architect/issues/1233), but this PR is a breaking change. We're going to do it, but we're going to have to pair it with some other changes as well.

I can keep it open as we get closer to this change in Arc 10, but there will be more to it than a find/replace of that env var.

**Comment by salper** [comment]
Thanks for your quick answer. That's indeed a breaking change, and you're probably the best person to assess if it needs more than a find and replace. Do you have any idea when the v10 would be released (or RC)?

**Comment by ryanblock** [comment]
Good news: as of this week I am full-time working on driving towards Arc 10. Not sure how long it'll take right now, but I'm optimistic it'll be early 2021. Stay tuned for some API proposals and an RC!

**Comment by ryanblock** [comment]
This change is now reflected in https://github.com/architect/functions/pull/513, shipping soon as Arc Functions v5!

**Pull request closed without merging**
