### PR TITLE
WIP

### PR DESCRIPTION
**Pull request by brianleroux**
should enable `return {sesson:{}}` to clear session data

### CODE REVIEW

**Comment by ryanblock** [comment]
Hmm, can we also allow you to return session undefined or null for the same effect?

**Comment by brianleroux** [comment]
no, I don't think we'd want that---this logic would mean if you forgot to assign a value to `session` the session would reset. another option is super explicit `session.destroy()`

**Comment by ryanblock** [comment]
Ah, good point. I dig it.

**Comment by brianleroux** [comment]
cc @kristoferjoseph wanna merge and test this with you (next week) … should clean things up a bit

**Pull request merged**
