### PR TITLE
chore: add `"sideEffects": false` to package.json

### PR DESCRIPTION
**Pull request by mcansh**
Add `"sideEffects": false` to package.json to allow frameworks that mix client and server code in the same files to tree-shake "@architect/functions" from client bundles.

https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles

https://esbuild.github.io/api/#conditionally-injecting-a-file
https://webpack.js.org/guides/tree-shaking
https://github.com/rollup/plugins/tree/master/packages/node-resolve#ignoresideeffectsforroot

### We really appreciate your commitment to improving Architect

To maintain a high standard of quality in our releases, before merging every pull request we ask that you've completed the following:

- [x] Forked the repo and created your branch from `main`
- [x] Made sure tests pass (run `npm it` from the repo root)
- [ ] Expanded test coverage related to your changes:
  - [ ] Added and/or updated unit tests (if appropriate)
  - [ ] Added and/or updated integration tests (if appropriate)
- [ ] Updated relevant documentation:
  - [ ] Internal to this repo (e.g. `readme.md`, help docs, inline docs & comments, etc.)
  - [ ] [Architect docs (arc.codes)](https://github.com/architect/arc.codes)
- [ ] Summarized your changes in `changelog.md`
- [ ] Linked to any related issues, PRs, etc. below that may relate to, consume, or necessitate these changes

Please also be sure to completed the CLA (if you haven't already).

Learn more about [contributing to Architect here](https://arc.codes/intro/community).

Thanks again!

### CODE REVIEW

**Comment by ryanblock** [comment]
Hey there! I am not certain all our exports are side effect free per webpack’s definitions. I don’t want to make claims to bundlers that we are uncertain of, just to have to support the issues that could cause later. Wdyt?

**Comment by ryanblock** [comment]
Related, I’m not sure I follow what you mean by tree shaking fs-extra, that is not a dependency of this lib.

**Comment by mcansh** [comment]
> Hey there! I am not certain all our exports are side effect free per webpack’s definitions. I don’t want to make claims to bundlers that we are uncertain of, just to have to support the issues that could cause later. Wdyt?

Makes sense and is totally a valid concern, I opened this without _really_ looking at any related code, having a re-export for `export {default} from "@architect/functions";` is sufficient enough - was just trying to make the integration into \[Remix\](https://remix.run) projects a bit easier

> Related, I’m not sure I follow what you mean by tree shaking fs-extra, that is not a dependency of this lib.

sorry! copy paste gone bad, should be "@architect/functions"

**Comment by ryanblock** [comment]
I'd say things are pretty pure, the only thing that gives me pause is https://github.com/architect/functions/blob/main/src/index.js#L43-L45

Since I'm not familiar with the ramifications of this change and will wind up being responsible for things breaking should we make it, how do you think we should go about resolving this PR?

**Comment by mcansh** [comment]
hm, yeah that does make me hesitant, plus based on the "tip" from the [webpack docs](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) it sounds like we shouldn't do this - I'll ask around on our side

**Pull request closed without merging**
