### PR TITLE
V4 rebased

### PR DESCRIPTION
**Pull request by filmaj**
Please review @brianleroux. This is your v4 branch rebased w/ latest master.

Two things: 
- I [`skip`ed one of the `proxy.read` tests](https://github.com/architect/functions/compare/master...filmaj:v4-rebased?expand=1#diff-713f6ab12a44aaa74b366dd8f83b6f8eR11) as I'm not sure that it would work in a sandbox context? Need your opinion on that one.
- The express-style middleware test I added recently is failing. Looks like middleware that return a response object using the `res` function argument passed to the middleware isn't being returned in the final handler.

Other than that looks fine, but let's see what the CI says...

### CODE REVIEW

**Comment by brianleroux** [comment]
don't think I understand this test https://github.com/filmaj/functions/blob/v4-rebased/test/unit/http/http-test.js#L21 arc.http returns a lambda sig `(event, context, callback)=>` and we expect it to invoke `callback` ala `callback(null, {payload})`

**Comment by filmaj** [comment]
@brianleroux ah ok, I guess the expectation around what an 'express style sig' means is what is at stake. I thought we expected that middleware handler functions are given (`req, `res`, `next`) arguments, where `res` is a function that takes an HTTP response object as parameter.

This particular test was passing before your v4 changes FWIW.

**Comment by brianleroux** [comment]
Your description is correct! `arc.http` accepts functions of the sig `(req, res, next)=>` as arguments. 

`arc.http` itself returns a function composed of those above functions that returns void. The lambda or sandbox runtime will invoke the composed function with `(event, context, callback)=>`. we run the express-y functions in series with the final result being passed thru to the invoking runtime via a classic Node errback param `callback`.

if this sounds like nonsense lmk / could kick up a zoom and talk it thru

**Comment by brianleroux** [comment]
> I skiped one of the proxy.read tests as I'm not sure that it would work in a sandbox context? Need your opinion on that one.

proxy.read should work in the sandbox! https://github.com/architect/functions/blob/v4/src/http/proxy/read.js#L28

**Comment by filmaj** [comment]
Chatted this through with Bri, was my bad, was misunderstanding how `bind` works and what is expected in these changes w.r.t. `arc.http`. Will tweak the test to address that. Will also dig further into `proxy` functionality to figure out how best to unit test it. Gonna assign this one to myself and ping folks for review once ready.

**Comment by filmaj** [comment]
I deployed an app using architect/cli and this branch of functions and it works!!!

So I'm fine merging this in @brianleroux

**Comment by filmaj** [comment]
Closed in favour of #50

**Pull request closed without merging**
